Algorithms
McDusia/predictParcels pull request #9
Opened 2020-04-24 21:00 UTC by McDusia

Please review the code

2020-04-25 20:40 UTC, dykra requested changes

2020-04-25 20:40 UTC, dykra commented on DescribeDataToTrainModel.txt
> +           OBJECTID      PERIMETER     PARCEL_TYP  LAND_Curr_Roll_Yr  IMPROVE_Curr_Roll_YR  IMPROVE_Curr_Value  Recording_Date  Hmownr_Exempt_Number  Hmownr_Exempt_Value  LS1_Sale_Date  LS2_Sale_Date
co to jest za plik?

2020-04-25 20:40 UTC, dykra commented on utils/serialization_module.py
> +def serialization_object_decorate(
to jest serialziacja jaka byla w inzynierce? :D bo nie pameitam juz

2020-04-25 20:40 UTC, dykra commented on analyze_data.py
> +                                                                 parcel_prices_mapping[current_bucket],
Czemu zakladamy ze chcemy analizowac dane tylko dla jednego rodzaju dzialek?

2020-04-25 20:40 UTC, dykra commented on analyze_data.py
> +    # Type: dataframe
jak dla mnie komentarz do usuniecia, nie wnosi za duzo

2020-04-25 20:40 UTC, dykra commented on analyze_data.py
> +    # What is the .groupby('LS2_Sale_Date')
komentarze do usuniecia

2020-04-25 20:40 UTC, dykra commented on analyze_data.py
> +    # What is the .groupby('LS2_Sale_Date')
chyba ze opisac wiecej co oznacza zakomentowany kod jesli to jest potejclanie pomocne na przyszlosc

2020-04-25 20:40 UTC, dykra commented on db_scripts/AddNewParameters.sql
> +ALTER TABLE PARCEL_VECTORS
Patrzylas na kod ktory ja robilam wgl? Mamy osobna tabele PARCEL_DESTINATIONS czy jakos tak. Fajnie byloby jednak trzmac sie jednej konwencji

2020-04-25 20:40 UTC, dykra commented on db_scripts/CreateSpatialIndexesForNewTables.sql
> +WITH (BOUNDING_BOX =(6275487.79, 1384146.14, 6668480.77, 2122084.6),
Co oznacza ten BOUNDING_BOx? czemu tutaj sa zahardcodowane wartosci? Czym one sa?

2020-04-25 20:40 UTC, dykra commented on db_scripts/Load_new_data_to_database.sql
> +    FROM 'C:\Magdalena\MAGISTERKA\predictParcels\db_scripts\data\Public_Elementary_Schools.csv'	-- Here change path
hm moze jednak wyniesc to do zmiennej na gore skryptu?

2020-04-25 20:40 UTC, dykra commented on db_scripts/Load_new_data_to_database.sql
> +    ERRORFILE = 'C:\Magdalena\MAGISTERKA\predictParcels\db_scripts\data\ep_errors.txt',	-- Here change path
to samo jak wyzej ( do zmiennej)

2020-04-25 20:40 UTC, dykra commented on db_scripts/Load_new_data_to_database.sql
> +    FROM 'C:\Magdalena\MAGISTERKA\predictParcels\db_scripts\data\Public_Middle_Schools.csv'	-- Here change path
jak wyzej

2020-04-25 20:40 UTC, dykra commented on db_scripts/Load_new_data_to_database.sql
> +    ERRORFILE = 'C:\Magdalena\MAGISTERKA\predictParcels\db_scripts\data\ep_errors.txt',	-- Here change path
jak wyzej

2020-04-25 20:40 UTC, dykra commented on db_scripts/Load_new_data_to_database.sql
> +    FROM 'C:\Magdalena\MAGISTERKA\predictParcels\db_scripts\data\Public_High_Schools.csv'	-- Here change path
jak wyzej ( nizej juz nie bd pisac, przy tych zmianach po prostu najpioej bd wyszukac wszystkie te uzycia)

2020-04-25 20:40 UTC, dykra commented on db_scripts/ProceduresToCountDistancesBetweenParcelsAndPOI.sql
> +--	@index_stop = 1000000
delete unnecessary code

2020-04-25 20:40 UTC, dykra commented on db_scripts/retrieveData/sp_get_Data.sql
> +CREATE OR ALTER PROCEDURE dbo.GetDateToTrainModelWithoutPriceParametersImportantAttributes
Po co jest ta procedura? przeciez mamy proicedure do poebirania danych. I ona ma juz swoja nazwe. Jesli chcemy ja zmienic to proponuje rename a nie nowa. NIe wiaodmo czym sie roznia itp.

2020-04-25 20:40 UTC, dykra commented on decision_tree/decision_tree.py
> +def get_data(database_handler):
mamy juz funkcje do tego. Nie duyplikujmy kody.

2020-04-25 20:40 UTC, dykra commented on decision_tree/decision_tree.py
> +    # training data - 55% of data, test data - 45 % of data
Jak ten komentarz ma sie do wartowci test_size=0.3? Jak dla mnie to nie zgadza sie i tylko wprowadza w blad.

2020-04-25 20:40 UTC, dykra commented on decision_tree/decision_tree.py
> +    print('Testing Labels Shape:', test_labels.shape)
Zmienic z logging.debug czy albo info

2020-04-25 20:40 UTC, dykra commented on decision_tree/decision_tree.py
> +    errors = abs(predictions_1 - test_labels)
Nie ma gotowego rozwiazania na licznei etych bledow?

2020-04-25 20:40 UTC, dykra commented on decision_tree/decision_tree.py
> +    plt.show()
Czy wyniki decision_tree mamy gdzies umieszczone w plikach txt? Fajnie byloby trzymac te wyniki na githubie tez. Lacznie z ywkresami.

2020-04-25 20:40 UTC, dykra commented on naive_bayes/naive_bayes.py
> +% (X_test.shape[0], (y_test != y_pred).sum()))
TO jest caly naive +bayes? troche nie rozumiem tego pliku. Poza tym nie uzywa naszych danych. Jak dla mnie nie nadaje sie do zmergowania do mastera.

2020-04-25 20:40 UTC, dykra commented on neural_network/neural_network.py
> +import numpy as np
to jest skopiowany kod z inzynierki?

2020-04-25 20:40 UTC, dykra commented on new_parameters/countDistance.js
> +console.out(distance)
co to za plik? wyglada jak plik testowy. Mozna w jakis utilsach zrobic opcje do liczenia odleglosci. Jak dla mnei do utils i mozna tam podfolder zrobic z jakimis potencjalnie przydatnycmi skrytpami testowymi.

2020-04-25 20:40 UTC, dykra commented on new_parameters/get_data
> +                    as_featureset=True)
tutaj jak wyzej. Czyli czy to ma jakis snes dla kodu> jesli n e to tez do utilsow pogtencjlanie pomocnych.

2020-04-25 20:40 UTC, dykra commented on neural_network/neural_network.py
> +import numpy as np
Nie wyglada ten plik na dokonczony.

2020-04-25 20:40 UTC, dykra commented on random_forest/random_forest.py
> +    y = data_to_train_model.iloc[:, data_size - 1]
drugi raz powtoraony kod do pobierania danych... nie mowiac o tym ze on juz jkest zaimplementowany i jest na mastzerze od dluzszego czasu , lepiej przelaczyc sie na jedna wersje.

2020-04-25 20:40 UTC, dykra commented on random_forest/random_forest.py
> +    # Instantiate model with 100 decision trees
gdzie jest 100 decision trees? nie widze nigfzie liczby 100. Jesli komentraz jest mylny to do usuniecia.

2020-04-25 20:40 UTC, dykra commented on random_forest/random_forest.py
> +    mape = 100 * (errors / test_labels)
drugi raz liczone errory. Jesli nie ma biblioteki do tego to wyniesc to do osobnego pliku.

2020-04-25 20:40 UTC, dykra commented on random_forest/tree.dot
> +digraph Tree {
co to za plik? do czsego jest potrzebnyt? jak go uzywac?

2020-04-25 20:40 UTC, dykra commented on requirements.txt
> +numpy
nie okreslamy wersji?

2020-04-25 20:40 UTC, dykra commented on utils/logger.py
> +def create_loggers_helper(logger):
po co nam ten logger? mozna uzywac logging.info() itp . nie trzeba tego loggera uzywac. ( wiem ze ja go pisalam ale potem sie zczailam ze nie potrzebne to jest :P)

2020-04-25 20:40 UTC, dykra commented on utils/plots.py
> +import logging
zmiana nazwy pliku. plots.py nie sugeruje co tutaj sie wykonywane :P moze opcje plotow do ryzoswania przyjmowac w parametrze? moga byc ustawione defaluty tez. ale w komenarzu w srodku opis jakie sa mozliwe wartosci parametrow.

2020-04-25 21:46 UTC, McDusia commented on DescribeDataToTrainModel.txt
> +           OBJECTID      PERIMETER     PARCEL_TYP  LAND_Curr_Roll_Yr  IMPROVE_Curr_Roll_YR  IMPROVE_Curr_Value  Recording_Date  Hmownr_Exempt_Number  Hmownr_Exempt_Value  LS1_Sale_Date  LS2_Sale_Date
to jest plik wygenerowany przez analyze_data.py, to początek dla kodu analizującego dane

2020-04-25 21:46 UTC, McDusia commented on utils/serialization_module.py
> +def serialization_object_decorate(
tak

2020-04-25 21:47 UTC, McDusia commented on utils/serialization_module.py
> +def serialization_object_decorate(
dodałam to wszystko, bo mamy sieć neuronową też dodaną

2020-04-25 21:49 UTC, McDusia commented on analyze_data.py
> +                                                                 parcel_prices_mapping[current_bucket],
aaa, rzeczywiście, źle jest

2020-04-25 21:50 UTC, McDusia commented on analyze_data.py
> +    # Type: dataframe
jak to? :o moim zdaniem bardzo dużo wnosi, bo wiadomo, że to co zwraca database_handler.execute_query to dataframe i wiadomo już jakich metod użyć jak chcemy dalej z tmy pracować

2020-04-25 21:54 UTC, McDusia commented on analyze_data.py
> +    # What is the .groupby('LS2_Sale_Date')
ok, opiszę

2020-04-25 21:55 UTC, McDusia commented on random_forest/random_forest.py
> +    mape = 100 * (errors / test_labels)
o widzisz, wiedziałam, że to mam zmienić, zapomniałam

2020-04-25 21:56 UTC, McDusia commented on random_forest/tree.dot
> +digraph Tree {
to jest zapamiętane drzewo decyzyjne ze zbudowanego modelu, można potem odczytać i narysować je używając takiego kodu: 
(graph,) = pydot.graph_from_dot_file('tree.dot')
    logger.info("Write graph to a png file")
    graph.write_png('tree.png')

2020-04-25 22:09 UTC, McDusia commented on requirements.txt
> +numpy
racja

2020-04-29 06:26 UTC, McDusia commented on analyze_data.py
> +                                                                 parcel_prices_mapping[current_bucket],
w zasadzie to może na razie zostać, bo trzeba dopisac nową procedurę żeby to zmienić, a i tak jest strasznie dużo tych danych, żeby na raz rysować wykresy dla wszystkich danych

2020-04-29 06:46 UTC, McDusia commented on utils/logger.py
> +def create_loggers_helper(logger):
ok, usuwam

2020-04-29 06:55 UTC, dykra commented on utils/plots.py
> +import logging
After messenger discussion - file to delete

2020-04-29 20:27 UTC, dykra commented on analyze_data.py
> +    # Type: dataframe
no ale zeby wiedziec co zwraca to moze lepiej otworzyc metode? przeciez nie mozna psiac komentarza do wszystkeigo co jest kodzie. zawsze mozna popatrzyc do dokumentacji pandas. zamiast komentarza woalalbvym naxzwe data_to_train_model_df -> gdzie df sugeruje ze to dataframe

2020-04-29 20:28 UTC, dykra requested changes

2020-04-29 20:28 UTC, dykra commented on analyze_data.py
> +                                                                 parcel_prices_mapping[current_bucket],
jesli trzeba pisac nowa procedure to na pewno to ne powinno byc w funckji get_data ktora nie sugeruje ze bedzie czesc danych. bo sie wszystko pomiesza

2020-05-13 22:49 UTC, McDusia commented on db_scripts/CreateSpatialIndexesForNewTables.sql
> +WITH (BOUNDING_BOX =(6275487.79, 1384146.14, 6668480.77, 2122084.6),
granice układu współrzędnych dla jakich ma być policzony indeks przestrzenny

2020-05-13 22:56 UTC, McDusia commented on new_parameters/countDistance.js
> +console.out(distance)
wywalam ten folder cały, na razie nic z tego się nie przyda

2020-05-13 22:57 UTC, McDusia commented on random_forest/random_forest.py
> +    y = data_to_train_model.iloc[:, data_size - 1]
połączone

2020-05-14 19:03 UTC, dykra approved these changes

2020-05-14 19:03 UTC, merged